services:
  redis:
    image: redis:7-alpine
    container_name: msif-redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msif-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
