services:
  db:
    image: mysql:8.0
    container_name: msif-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: msif_ninos_felices
      MYSQL_USER: msif_user
      MYSQL_PASSWORD: msif_pass
      TZ: America/Lima
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 360s

  redis:
    image: redis:7-alpine
    container_name: msif-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msif-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/msif_ninos_felices?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: msif_user
      SPRING_DATASOURCE_PASSWORD: msif_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    restart: unless-stopped

volumes:
  db_data:
